### ISSUE TITLE
Harvest Level 0 doesn't show

### ISSUE THREAD

**Issue by Julienraptor01** [shedaniel/can-i-mine-this-block#10]
I have 2 problems

-first harvest level 0 don't appear
-~~second the reported harvest level are wrong~~

![2022-03-03_01 39 16](https://user-images.githubusercontent.com/49841713/156473819-1d454884-1e0e-42d7-af39-dd1a3ce51a18.png)
(we can mine stone with wood or gold)

![2022-03-03_01 39 21](https://user-images.githubusercontent.com/49841713/156473835-5b36137e-a392-4c98-b2a5-2d12a6fffaf4.png)
(we can mine iron with stone)

![2022-03-03_01 39 36](https://user-images.githubusercontent.com/49841713/156473840-1b3178ba-2ad9-4d94-8ccf-d73c58fd87fc.png)
(we can mine diamond with iron)

![2022-03-03_01 39 42](https://user-images.githubusercontent.com/49841713/156473847-596ff8c7-dc67-4008-b244-acef7418b530.png)
(we can mine ancient debris with diamond)

(and with netherite we should be able to mine the next thing but i'm in vanilla so the next thing doesn't exist)

i will make a PR to fix this as i translate in french.

**Comment by Julienraptor01** [comment]
So now that the second incomprehension is clear there's still the first problem which is that harvest level 0 doesn't show.

**Comment by shedaniel** [comment]
This is intended
