### ISSUE TITLE
Using with WTHIT on Fabric 1.18.2; wrong harvestability level displayed

### ISSUE THREAD

**Issue by Geethebluesky** [shedaniel/can-i-mine-this-block#19]
Is this meant to be compatible with WTHIT?
This very smart person likes to see harvestability for mods that add extra ore tiers, so I installed this (using Fabric 1.18.2) and am using it with WTHIT.

It's showing me Deepslate Gold and Redstone as requiring "Diamond (2)" instead of Iron.
Thanks for letting me know if this is fixable or if it's just not meant to be compatible.

**Comment by rdrpenguin04** [comment]
It's intentional. Diamond harvest level means a pickaxe that can mine diamonds. This behavior is a relic from Tinkers' Construct harvestability levels in case you're curious.

**Comment by Geethebluesky** [comment]
Oh thanks, I didn't realize it looked at what it can do instead of what it's made of! I appreciate the tip.

**Comment by rdrpenguin04** [comment]
If this solved the problem, you should close the issue 😄

**Comment by shedaniel** [comment]
Thanks
