### ISSUE TITLE
Create Quilt Loader version?

### ISSUE THREAD

**Issue by arenekosreal** [shedaniel/can-i-mine-this-block#20]
Quilt Loader is a newly Minecraft loader based on Fabric, it says most Fabric mods can run directly on Quilt, while this mod may be an exception. On recent Minecraft releases, we have to use WTHIT to provide HWYLA and WTHIT has a Quilt version, but this mod can't run with the Quilt version of WTHIT.

Here is the website of Quilt: https://quiltmc.org/

**Comment by shedaniel** [comment]
I don't have time to prioritise Quilt development. I was told Quilt supports Fabric mods, this mod does nothing special, imagine the time required if every one of my mods needs porting, WTHIT should fix the incompatibility, not me.

**Comment by deirn** [comment]
@zhanghua000 
It does work with WTHIT Quilt, [see this gist](https://gist.github.com/deirn/df5586a7e883c0440a38d50f402b8a09#file-gistfile1-txt-L212), can you send me your log?

**Comment by arenekosreal** [comment]
Never mind, I find that this problem disappears when I restart game to get a clean log. Anyway, thanks for your help to solve this problem.
