### ISSUE TITLE
netherite harvest level reported as Metite

### ISSUE THREAD

**Issue by superon** [shedaniel/can-i-mine-this-block#5]
"cimtb.harvest_level.level.4": "§dMetite",
should be
  "cimtb.harvest_level.level.4": "§dNetherite",
or
  "cimtb.harvest_level.level.4": "§8Netherite",

**Comment by shedaniel** [comment]
no, it indicates what kind of material can be mined on that level, netherite can be mined with a level 3 pick, metite can be mined with a level 4 pick
